### PR TITLE
added README.MD

### PR DESCRIPTION
**Pull request by Rooosss**

### CODE REVIEW

**Review by Rooosss — COMMENTED** [review]
added readme.md

**Comment by Rooosss** [comment]
added readme.md

**Comment by anna-vrana-moc** [comment]
Hey, @Rooosss! Please delete the package-lock.json file from your pull request (PR)

**Comment by anna-vrana-moc** [comment]
It might be useful to you
Screenshot 2023-10-13 at 05 58 30

**Pull request closed without merging**
