### PR TITLE
Сreated login page, success login page.

### PR DESCRIPTION
**Pull request by LotusElize**
Created a login page with a form, implemented email field validation, concealed the password, added focus on label click, and created a success login page with a 'Return to homepage' button for redirection

### CODE REVIEW

**Review by MZabolotnev — CHANGES_REQUESTED** [review]
1) When I fill in both fields but don't click the checkbox, I can't submit the form and I don't see any errors
2) Buttons should have a pointer cursor when hovering

**Comment by LotusElize** [comment]
Hello, Of course you can't submit the form if you don't check the checkbox. All the inputs have the required attribute, which means that they are all required to be filled in before the form can be submitted.
"I don't see any errors " Erors when checkbox is not checked ?
Is there a way to implement this other than with the required attribute in HTML?


In the homework, it is indicated that the form should not be sent if the checkbox is not checked (or the mail or password fields), there seems to be nothing about errors.
"If the checkbox is not checked, or if the email or password fields are not filled in, the form should not be sent."

**Comment by MZabolotnev** [comment]
> @MZabolotnev Hello, you can't submit the form if you don't check the checkbox. All the inputs have the required attribute, which means that they are all required to be filled in before the form can be submitted. "I don't see any errors " Erors when checkbox is not checked ? Is there a way to implement this other than with the required attribute in HTML?
> 
> In the homework, it is indicated that the form should not be sent if the checkbox is not checked (or the mail or password fields), there seems to be nothing about errors. "If the checkbox is not checked, or if the email or password fields are not filled in, the form should not be sent."

This is an example of bad UI. From the user's point of view - he cannot send the form and does not understand why. Now you don't see a about validation message through display:none. Try another way or use default checkbox

**Comment by LotusElize** [comment]
@MZabolotnev Thanks, check now please.

**Review by MZabolotnev — APPROVED** [review]

**Pull request merged**
