### PR TITLE
1 html yana dankova

### PR DESCRIPTION
**Pull request by YanaDankova**

### CODE REVIEW

**Comment by anna-vrana-moc** [comment]
Hi @YanaDankova please fix small issues)

**Comment by YanaDankova** [comment]
Thank you. But I don’t understand what I should fix. Where I should look at
it?

сб, 21 жовт. 2023 р. о 11:25 anna-vrana-MOC ***@***.***> пише:

**Comment by anna-vrana-moc** [comment]
All issues you can find as a comment on the GitHub

**Comment by anna-vrana-moc** [comment]
@YanaDankova you can find new recommendations, so go ahead and fix fonts and link

**Comment by YanaDankova** [comment]
I changed link and font.

**Review by anna-vrana-moc — APPROVED** [review]

**Pull request merged**
