### PR TITLE
homework #4, js basics

### PR DESCRIPTION
**Pull request by SashaDemi**

### CODE REVIEW

**Comment by vladyslav-yermolin-moc** [comment]
Hey, @SashaDemi, next time you can assign me for your pull request here. It can increase the speed of checking your pr.
image

**Comment by SashaDemi** [comment]
Hi, Vlad. Thanks for your comment.
I think i did it one time. 
Maybe i need do it every pull request?

**Review by vladyslav-yermolin-moc — APPROVED** [review]
It would be better to avoid abbreviations, cause for you  `numb` = `number` is obvious, but somebody else could be confused.
image

**Comment by vladyslav-yermolin-moc** [comment]
Sure: every new pull request is a new change, that you like to merge to the main branch (~production). So them should be treat separately and one by one.

**Pull request merged**
