### PR TITLE
2-css_snischuk

### PR DESCRIPTION
**Pull request by snischuk**
пока на флексах)

### CODE REVIEW

**Comment by anna-vrana-moc** [comment]
Hey @snischuk please improve your code :)

**Comment by snischuk** [comment]
> Hey @snischuk please improve your code :)

Please specify what should I need improve? (only change to grid layout or anything else?)

**Comment by anna-vrana-moc** [comment]
I've commented on your code: [pokemons.html] and [index.css]( I suggest creating different CSS files for each page)

**Comment by snischuk** [comment]
add BEM class naming and module file structure

**Comment by snischuk** [comment]
changed flex to grid

**Review by anna-vrana-moc — APPROVED** [review]

**Comment by anna-vrana-moc** [comment]
Great job! Approved

**Pull request merged**
